// tslint:disable
/**
 * Test Work Helmes
 * Test Work for Helmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI } from '../runtime';
import {
    Sector,
} from '../models';

/**
 * no description
 */
export class SectorsApi extends BaseAPI {

    /**
     */
    getSectors = (): Observable<Array<Sector>> => {
        return this.request<Array<Sector>>({
            path: '/sectors',
            method: 'GET',
        });
    };

}
