// tslint:disable
/**
 * Test Work Helmes
 * Test Work for Helmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI } from '../runtime';
import {
    ApiError,
    UserSelect,
    UserSelectRequest,
} from '../models';

export interface CreateUserSelectRequest {
    userSelectRequest: UserSelectRequest;
}

export interface UpdateUserSelectRequest {
    id: number;
    userSelectRequest: UserSelectRequest;
}

/**
 * no description
 */
export class UsersApi extends BaseAPI {

    /**
     */
    createUserSelect = ({ userSelectRequest }: CreateUserSelectRequest): Observable<UserSelect> => {
        throwIfNullOrUndefined(userSelectRequest, 'createUserSelect');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<UserSelect>({
            path: '/users/user-select',
            method: 'POST',
            headers,
            body: userSelectRequest,
        });
    };

    /**
     */
    updateUserSelect = ({ id, userSelectRequest }: UpdateUserSelectRequest): Observable<UserSelect> => {
        throwIfNullOrUndefined(id, 'updateUserSelect');
        throwIfNullOrUndefined(userSelectRequest, 'updateUserSelect');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<UserSelect>({
            path: '/users/user-select/{id}'.replace('{id}', encodeURI(id)),
            method: 'PUT',
            headers,
            body: userSelectRequest,
        });
    };

}
