// tslint:disable
/**
 * Test Work Helmes
 * Test Work for Helmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApiErrorItem
 */
export interface ApiErrorItem {
    /**
     * @type {string}
     * @memberof ApiErrorItem
     */
    message?: string;
    /**
     * @type {Array<string>}
     * @memberof ApiErrorItem
     */
    args?: Array<string>;
}
