// tslint:disable
/**
 * Test Work Helmes
 * Test Work for Helmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Sector
 */
export interface Sector {
    /**
     * @type {number}
     * @memberof Sector
     */
    value?: number;
    /**
     * @type {string}
     * @memberof Sector
     */
    name?: string;
    /**
     * @type {number}
     * @memberof Sector
     */
    parent?: number;
}
