// tslint:disable
/**
 * Test Work Helmes
 * Test Work for Helmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UserSelect
 */
export interface UserSelect {
    /**
     * @type {number}
     * @memberof UserSelect
     */
    id?: number;
    /**
     * @type {string}
     * @memberof UserSelect
     */
    name?: string;
    /**
     * @type {Array<number>}
     * @memberof UserSelect
     */
    sectors?: Array<number>;
    /**
     * @type {boolean}
     * @memberof UserSelect
     */
    agreedWithTerms?: boolean;
}
